### ISSUE TITLE
关于我

### ISSUE THREAD

**Issue by AlynxZhou** [RinChanNOWWW/rinchannowww.github.io#4]
我来抢沙发，有什么关于这个主题的问题或者建议可以直接联系我（虽然我很懒就是了），如果方便可以交换友链 <https://sh.alynx.xyz/>。（逃

**Comment by dongshunyao** [comment]
色图呢！说好的色图呢？！

**Comment by AlynxZhou** [comment]
@dongshunyao 你这只鸽子只知道色图！
